name: flutter_live_shop
description: A Flutter project for an electronic shopping mall.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  # Socket.IO 客戶端
  socket_io_client: ^2.0.3
  # 或使用 ASP.NET Core SignalR
  signalr_netcore: ^1.3.7

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter   # ✅ 必加
  
  flutter_inappwebview: ^6.0.0

  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  video_player: ^2.9.1
  chewie: ^1.7.5  # 可切換播放控制
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.16.1
  webview_flutter_wkwebview: ^3.13.1
  webview_flutter_platform_interface: ^2.9.0
  webview_flutter_web: ^0.2.2+5 # 讓 web 也能以同介面工作
  # 如需 WebRTC 直播可改採 livekit_client / flutter_webrtc
  # HTTP client for backend API (use 1.x to be compatible with signalr_netcore)
  http: ^1.5.0
  dio: ^5.9.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true