name: eshop_flutter_vip
description: Flutter e-commerce skeleton with VIP levels, live, chat, auth
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  cached_network_image: ^3.3.1

  # Live
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.1
  webview_flutter_wkwebview: ^3.13.1
  webview_flutter_web: ^0.2.2+5
  pointer_interceptor: ^0.9.3

  # Chat (both options; default Mock used)
  socket_io_client: ^2.0.3
  signalr_netcore: ^1.3.7

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
